<?php
return [
    'experience' => [
        ['id'=>'0','name'=>'Chưa có kinh nghiệm'],
        ['id'=>'1','name'=>'Dưới 1 năm kinh nghiệm'],
        ['id'=>'2','name'=>'1 năm kinh nghiệm'],
        ['id'=>'3','name'=>'2 năm kinh nghiệm'],
        ['id'=>'4','name'=>'3 năm kinh nghiệm'],
        ['id'=>'5','name'=>'4 năm kinh nghiệm'],
        ['id'=>'6','name'=>'5 năm kinh nghiệm'],
        ['id'=>'7','name'=>'Trên 5 năm kinh nghiệm'],
    ],
    'type_work' => [
        ['id'=>'0','name'=>'Thực tập'],
        ['id'=>'1','name'=>'Bán thời gian'],
        ['id'=>'2','name'=>'Toàn thời gian'],
        ['id'=>'3','name'=>'Tại nhà'],
    ],
    'gender' => [
        ['id'=>'0','name'=>'--Chọn--'],
        ['id'=>'1','name'=>'Nam'],
        ['id'=>'2','name'=>'Nữ'],
    ],
    'level' => [
        ['id'=>'0','name'=>'Thực tập sinh'],
        ['id'=>'1','name'=>'Nhân viên'],
        ['id'=>'2','name'=>'Trưởng nhóm'],
        ['id'=>'3','name'=>'Trưởng/phó phòng'],
        ['id'=>'4','name'=>'Trưởng chi nhánh'],
        ['id'=>'5','name'=>'Phó giám đốc'],
        ['id'=>'6','name'=>'Giám đốc'],
    ],
    'type_salary' => [
        ['id'=>'0','name'=>'Trong khoảng'],
        ['id'=>'1','name'=> 'Từ'],
        ['id'=>'2','name'=>'Đến'],
        ['id'=>'3','name'=>'Thỏa thuận'],
    ],
    'area' => [
        ['id'=>'0','name'=>'Hà Nội'],
        ['id'=>'1','name'=> 'Đà Nẵng'],
        ['id'=>'2','name'=>'TP Hồ Chí Minh'],
    ],
    'skill' => [
        ['id'=>'0','name'=>'PHP'],
        ['id'=>'1','name'=> 'HTML'],
        ['id'=>'2','name'=>'JavaScript'],
        ['id'=>'3','name'=>'CSS'],
        ['id'=>'4','name'=>'Java'],
        ['id'=>'5','name'=>'Work'],
    ],
    'job_post_status' => [
        'block' => '0',
        'active' => '1',
    ],
    'type_degree' => [
        ['id'=>'Đại học','name'=>'Đại học'],
        ['id'=>'Cao đẳng','name'=>'Cao đẳng'],
        ['id'=>'Trung cấp','name'=>'Trung cấp'],
        ['id'=>'Sau đại học (Thạc sỹ/Tiến sĩ)','name'=>'Sau đại học (Thạc sỹ/Tiến sĩ)'],
        ['id'=>'Trung tâm đào tạo','name'=>'Trung tâm đào tạo'],
        ['id'=>'Du học','name'=>'Du học'],
    ],
    'marital' => [
        ['id'=>'Độc thân', 'name'=> 'Độc thân'],
        ['id'=>'Đã kết hôn','name' => 'Đã kết hôn'],
        ['id'=>'Hẹn hò','name' => 'Hẹn hò'],
        ['id'=>'Tìm hiểu','name' => 'Tìm hiểu'],
        ['id'=>'Đã đính hôn','name' => 'Đã đính hôn'],
        ['id'=>'Đã ly thân','name' => 'Đã ly thân'],
        ['id'=>'Đã ly hôn','name' => 'Đã ly hôn'],
        ['id'=>'Góa','name' => 'Góa'],
    ],
];
